[package]
name = "spartan-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
acir = { path = "../../noir/acvm-repo/acir", features = ["t256"] }
bellpepper-core = "0.4.0"
ff = "0.13.1"
noirc_abi = { path = "../../noir/tooling/noirc_abi" }
noirc_artifacts = { path = "../../noir/tooling/noirc_artifacts" }
num-bigint = {version="0.4.3", features = ["rand"]}
num-traits = "0.2.14"
serde_json = { version = "1.0", features = ["unbounded_depth"] }
spartan2 = { version = "0.7.0", default-features = false}
log = "0.4.29"
env_logger = "0.11.10"
