use crate::noir::circuit::CircuitParameters;
use crate::noir::circuit_reader::types::circuit_input::CircuitInput;
use crate::noir::circuit_reader::prover_input_mapping::{read_inputs};
use crate::noir::circuit_reader::read_noir_circuit;
use crate::noir::circuit_reader::types::input_wire::InputWire;
use crate::noir::circuit_reader::verifier_input_mapping::read_verifier_inputs;
use crate::Scalar;

struct CircuitSettings {
    circuit_file: String,
    prover_inputs_file: String,
    verifier_inputs_file: String,
}

impl CircuitSettings {
    const BASE_PATH: &'static str = "../circuits";

    pub fn new(name: &str) -> CircuitSettings {
        CircuitSettings {
            circuit_file: format!("{}/{}/target/{}.json", Self::BASE_PATH, name, name),
            prover_inputs_file: format!("{}/{}/target/{}.gz", Self::BASE_PATH, name, name),
            verifier_inputs_file: format!("{}/{}/verifier_input.json", Self::BASE_PATH, name),
        }
    }
}

pub fn map_into_field_flat(
    inputs: &Vec<InputWire<CircuitInput>>,
) -> Vec<InputWire<Option<Scalar>>> {

    inputs.iter()
        .map(|input_wire|
            input_wire.clone_with_value(input_wire.value.to_scalar())
        )
        .collect()
}

pub fn instantiate_circuit(name: &str) ->  CircuitParameters {
    let circuit_settings = CircuitSettings::new(name);

    let program_artifact = read_noir_circuit(circuit_settings.circuit_file.as_str())
        .expect("Failed to read noir circuit");

    // map prover inputs from gz generated by Nargo
    let mapped_prover_input = read_inputs(
        &program_artifact,
        circuit_settings.prover_inputs_file.as_str()
    );
    tracing::debug!("Prover inputs: {:?}", mapped_prover_input);
    let field_prover_input = map_into_field_flat(&mapped_prover_input);
    // each wire has to be assigned for the prover
    assert!(field_prover_input.iter().all(|input_wire| input_wire.value.is_some()));

    // map verifier inputs from json
    let mapped_verifier_input = read_verifier_inputs(
        &program_artifact,
        circuit_settings.verifier_inputs_file.as_str()
    );
    tracing::debug!("Verifier inputs: {:?}", mapped_verifier_input);
    let field_verifier_input = map_into_field_flat(
        &mapped_verifier_input
    );

    CircuitParameters {
        name: String::from(name),
        program_artifact,
        prover_inputs: field_prover_input.clone(),
        verifier_inputs: field_verifier_input,
    }
}